module.exports = {
  "gradient-shift": "gradient-shift 12s ease-in-out infinite",
  "spin-slow": "spin 3s linear infinite",
  "spin-fast": "spin 0.5s linear infinite",
  "ping-slow": "ping 2s cubic-bezier(0, 0, 0.2, 1) infinite",
  "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
  "bounce-slow": "bounce 2s infinite",
  "fade-in": "fadeIn 0.5s ease-out",
  "fade-out": "fadeOut 0.5s ease-in",
  "slide-up": "slideUp 0.3s ease-out",
  "slide-down": "slideDown 0.3s ease-out",
  "scale-in": "scaleIn 0.2s ease-out",
  "scale-out": "scaleOut 0.2s ease-in",
  "rotate-in": "rotateIn 0.3s ease-out",
  "rotate-out": "rotateOut 0.3s ease-in",
  "flip-in": "flipIn 0.6s ease-out",
  "flip-out": "flipOut 0.6s ease-in",
  "zoom-in": "zoomIn 0.3s ease-out",
  "zoom-out": "zoomOut 0.3s ease-in",
  "shake": "shake 0.5s ease-in-out",
  "wiggle": "wiggle 0.5s ease-in-out",
  "float": "float 3s ease-in-out infinite",
  "sink": "sink 3s ease-in-out infinite",
  "glow": "glow 2s ease-in-out infinite alternate",
  "shimmer": "shimmer 2s linear infinite",
  "gradient": "gradient 3s ease infinite",
  "morph": "morph 4s ease-in-out infinite",
  "serviceSwitch": "serviceSwitch 0.3s ease-in-out",
  "modal-appear": "modal-appear var(--duration-normal) var(--ease-out)",
  "loading-shimmer": "loading-shimmer 1.5s infinite",
  "glass-fade-in": "glass-fade-in var(--duration-slow) var(--ease-out)"
};
