# [[headers]]
#   for = "/*"
#   [headers.values]
#     Cross-Origin-Opener-Policy = "same-origin"
#     Cross-Origin-Embedder-Policy = "require-corp"
#     Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.googleapis.com;"
[[headers]]
  for = "/*"
  [headers.values]
    # Cross-origin policies recommended for security; adjust if needed for your deployment.
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

    # Content-Security-Policy:
    # - We add a placeholder backend domain (api.your-backend.tld) to connect-src so the browser may
    #   establish WebSocket / fetch connections to the production FastAPI backend.
    # - Replace the placeholder with your actual backend domain in production.
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.googleapis.com https://api.your-backend.tld;"

# Optional redirects: If you'd rather have Netlify route /api/* to your backend (rewrite),
# you can enable a redirect rule below. This is commented out as an example.
#
# [[redirects]]
#   from = "/api/*"
#   # :splat is replaced with the matched path fragment
#   to = "https://api.your-backend.tld/:splat"
#   status = 200
#   force = true
#
# Notes:
# - Use the rewrite above to forward requests from the Netlify-hosted frontend to your backend domain
#   without changing client-side code (client still calls /api/*).
# - Alternatively, set VITE_ADMIN_API_URL in the frontend to the backend origin and call it directly.
