// List of OBS WebSocket event names and friendly descriptions
// Reference: https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#events

export interface OBSEventInfo {
  name: string;
  description: string;
}

export const OBS_EVENT_LIST: OBSEventInfo[] = [
  { name: 'CurrentProgramSceneChanged', description: 'The current program scene has changed.' },
  {
    name: 'CurrentPreviewSceneChanged',
    description: 'The current preview scene has changed (Studio Mode).',
  },
  { name: 'SceneCreated', description: 'A new scene was created.' },
  { name: 'SceneRemoved', description: 'A scene was removed.' },
  { name: 'SceneNameChanged', description: 'A scene was renamed.' },
  { name: 'InputCreated', description: 'A new input (source) was created.' },
  { name: 'InputRemoved', description: 'An input (source) was removed.' },
  { name: 'InputNameChanged', description: 'An input (source) was renamed.' },
  { name: 'InputActiveStateChanged', description: 'An input became active/inactive.' },
  { name: 'InputShowStateChanged', description: 'An input became shown/hidden.' },
  { name: 'InputMuteStateChanged', description: 'An input was muted/unmuted.' },
  { name: 'InputVolumeChanged', description: 'The volume of an input changed.' },
  { name: 'InputAudioBalanceChanged', description: 'The audio balance of an input changed.' },
  {
    name: 'InputAudioSyncOffsetChanged',
    description: 'The audio sync offset of an input changed.',
  },
  { name: 'InputAudioTracksChanged', description: 'The audio tracks of an input changed.' },
  {
    name: 'InputAudioMonitorTypeChanged',
    description: 'The audio monitor type of an input changed.',
  },
  { name: 'InputVolumeMeters', description: 'Volume meter levels for an input.' },
  { name: 'InputSettingsChanged', description: 'The settings of an input changed.' },
  { name: 'InputPropertiesChanged', description: 'The properties of an input changed.' },
  {
    name: 'InputPropertiesListPropertyItemsChanged',
    description: 'A list property in input properties changed.',
  },
  { name: 'MediaInputPlaybackStarted', description: 'A media input started playback.' },
  { name: 'MediaInputPlaybackEnded', description: 'A media input finished playback.' },
  { name: 'MediaInputActionTriggered', description: 'A media input action was triggered.' },
  { name: 'SceneItemCreated', description: 'A scene item was created.' },
  { name: 'SceneItemRemoved', description: 'A scene item was removed.' },
  { name: 'SceneItemListReindexed', description: 'Scene items were reordered.' },
  { name: 'SceneItemEnableStateChanged', description: 'A scene item was enabled/disabled.' },
  { name: 'SceneItemLockStateChanged', description: 'A scene item was locked/unlocked.' },
  { name: 'SceneItemSelected', description: 'A scene item was selected.' },
  { name: 'SceneItemTransformChanged', description: 'A scene item transform changed.' },
  { name: 'SourceFilterCreated', description: 'A source filter was created.' },
  { name: 'SourceFilterRemoved', description: 'A source filter was removed.' },
  { name: 'SourceFilterNameChanged', description: 'A source filter was renamed.' },
  { name: 'SourceFilterEnableStateChanged', description: 'A source filter was enabled/disabled.' },
  { name: 'SourceFilterSettingsChanged', description: 'A source filter settings changed.' },
  { name: 'TransitionCreated', description: 'A transition was created.' },
  { name: 'TransitionRemoved', description: 'A transition was removed.' },
  { name: 'TransitionNameChanged', description: 'A transition was renamed.' },
  { name: 'TransitionDurationChanged', description: 'A transition duration changed.' },
  { name: 'TransitionSettingsChanged', description: 'A transition settings changed.' },
  { name: 'TransitionBegin', description: 'A transition started.' },
  { name: 'TransitionEnd', description: 'A transition ended.' },
  { name: 'TransitionVideoEnd', description: 'A transition video ended.' },
  { name: 'FilterCreated', description: 'A filter was created.' },
  { name: 'FilterRemoved', description: 'A filter was removed.' },
  { name: 'FilterNameChanged', description: 'A filter was renamed.' },
  { name: 'FilterEnableStateChanged', description: 'A filter was enabled/disabled.' },
  { name: 'FilterSettingsChanged', description: 'A filter settings changed.' },
  { name: 'RecordStateChanged', description: 'The record state changed.' },
  { name: 'RecordFileChanged', description: 'The record file changed.' },
  { name: 'ReplayBufferStateChanged', description: 'The replay buffer state changed.' },
  { name: 'ReplayBufferSaved', description: 'The replay buffer was saved.' },
  { name: 'VirtualcamStateChanged', description: 'The virtual camera state changed.' },
  { name: 'ReplayBufferSaved', description: 'The replay buffer was saved.' },
  { name: 'StreamStateChanged', description: 'The stream state changed.' },
  { name: 'StudioModeStateChanged', description: 'The studio mode state changed.' },
  { name: 'ScreenshotSaved', description: 'A screenshot was saved.' },
  { name: 'SceneCollectionListChanged', description: 'The scene collection list changed.' },
  { name: 'SceneCollectionChanged', description: 'The scene collection changed.' },
  { name: 'ProfileListChanged', description: 'The profile list changed.' },
  { name: 'ProfileChanged', description: 'The profile changed.' },
  { name: 'CurrentProfileChanged', description: 'The current profile changed.' },
  { name: 'CurrentSceneCollectionChanged', description: 'The current scene collection changed.' },
  { name: 'InputVolumeMeters', description: 'Input volume meters updated.' },
  { name: 'VendorEvent', description: 'A vendor-specific event.' },
  { name: 'CustomEvent', description: 'A custom event.' },
];
