/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { FunctionCallingRequestHistory } from './functionCallingRequestHistory';
import type { FunctionCallingRequestObsState } from './functionCallingRequestObsState';

export interface FunctionCallingRequest {
  /**
   * @minLength 1
   * @maxLength 5000
   */
  prompt: string;
  /** Model to use. */
  model?: string;
  history?: FunctionCallingRequestHistory;
  /** Current OBS state */
  obs_state?: FunctionCallingRequestObsState;
}
