/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */

export type Get7tvCosmeticsApiProxy7tvCosmeticsGetParams = {
/**
 * @minLength 1
 * @maxLength 50
 * @pattern ^[a-zA-Z0-9_]+$
 */
user_identifier: string;
};
