/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */

/**
 * Validation for image proxy URL.
 */
export interface ImageProxyRequest {
  /**
   * Valid image URL from allowed domains
   * @minLength 1
   * @maxLength 2083
   */
  image_url: string;
}
