/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { ImageGenerateRequestImageInput } from './imageGenerateRequestImageInput';
import type { ImageGenerateRequestImageInputMimeType } from './imageGenerateRequestImageInputMimeType';
import type { ImageGenerateRequestReferenceImages } from './imageGenerateRequestReferenceImages';
import type { ImageGenerateRequestImageSize } from './imageGenerateRequestImageSize';
import type { ImageGenerateRequestConditionType } from './imageGenerateRequestConditionType';

export interface ImageGenerateRequest {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  prompt: string;
  model?: string;
  /** @pattern ^(png|jpeg|webp)$ */
  image_format?: string;
  /** @pattern ^(1:1|3:4|4:3|9:16|16:9)$ */
  aspect_ratio?: string;
  /** @pattern ^(allow_adult|dont_allow)$ */
  person_generation?: string;
  image_input?: ImageGenerateRequestImageInput;
  image_input_mime_type?: ImageGenerateRequestImageInputMimeType;
  reference_images?: ImageGenerateRequestReferenceImages;
  image_size?: ImageGenerateRequestImageSize;
  search_grounding?: boolean;
  condition_type?: ImageGenerateRequestConditionType;
}
