/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { OBSActionArgs } from './oBSActionArgs';

/**
 * Represents a single command to be executed in OBS.
 */
export interface OBSAction {
  /** The OBS command to execute, e.g., 'SetCurrentProgramScene'. */
  command: string;
  /** A dictionary of arguments for the command. */
  args?: OBSActionArgs;
}
