/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { OBSAwareRequestObsState } from './oBSAwareRequestObsState';

export interface OBSAwareRequest {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  prompt: string;
  model?: string;
  /** Current OBS state */
  obs_state: OBSAwareRequestObsState;
  /** Use explicit caching for repeated contexts */
  use_explicit_cache?: boolean;
  /**
   * Cache TTL in minutes
   * @minimum 5
   * @maximum 120
   */
  cache_ttl_minutes?: number;
}
