/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { OBSAction } from './oBSAction';

/**
 * A structured response containing a series of OBS actions and the reasoning behind them.
 */
export interface OBSActionResponse {
  /** A list of OBS actions to be executed. */
  actions: OBSAction[];
  /** A step-by-step explanation of why these actions were chosen. */
  reasoning: string;
}
