/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { OBSActionArgsAnyOf } from './oBSActionArgsAnyOf';

/**
 * A dictionary of arguments for the command.
 */
export type OBSActionArgs = OBSActionArgsAnyOf | null;
