/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { PublishRequestMessage } from './publishRequestMessage';
import type { PublishRequestData } from './publishRequestData';

/**
 * Validation for overlay publish payload.
 */
export interface PublishRequest {
  /**
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-zA-Z0-9_]+$
   */
  channel: string;
  /** Message data */
  message?: PublishRequestMessage;
  /** Alternative data field */
  data?: PublishRequestData;
}
