/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */

export interface SpeechGenerateRequest {
  /**
   * @minLength 1
   * @maxLength 5000
   */
  prompt: string;
  /** The model to use for speech generation. */
  model?: string;
  isMultiSpeaker?: boolean;
  voice?: string;
  speaker1Voice?: string;
  speaker2Voice?: string;
}
