/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { VideoGenerateRequestAspectRatio } from './videoGenerateRequestAspectRatio';
import type { VideoGenerateRequestDurationSeconds } from './videoGenerateRequestDurationSeconds';
import type { VideoGenerateRequestPersonGeneration } from './videoGenerateRequestPersonGeneration';
import type { VideoGenerateRequestReferenceImages } from './videoGenerateRequestReferenceImages';
import type { VideoGenerateRequestImage } from './videoGenerateRequestImage';
import type { VideoGenerateRequestLastFrame } from './videoGenerateRequestLastFrame';
import type { VideoGenerateRequestVideo } from './videoGenerateRequestVideo';

export interface VideoGenerateRequest {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  prompt: string;
  model?: string;
  aspect_ratio?: VideoGenerateRequestAspectRatio;
  duration_seconds?: VideoGenerateRequestDurationSeconds;
  person_generation?: VideoGenerateRequestPersonGeneration;
  reference_images?: VideoGenerateRequestReferenceImages;
  image?: VideoGenerateRequestImage;
  last_frame?: VideoGenerateRequestLastFrame;
  video?: VideoGenerateRequestVideo;
}
