/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Universal Backend Server
 * A single backend to serve all my projects with Google AI integration.
 * OpenAPI spec version: 1.1.0
 */
import type { VideoGenerateRequestReferenceImagesAnyOfItem } from './videoGenerateRequestReferenceImagesAnyOfItem';

export type VideoGenerateRequestReferenceImages = VideoGenerateRequestReferenceImagesAnyOfItem[] | null;
