import { Theme } from './types/themes';
import {
  catppuccinLatteColors,
  catppuccinFrappeColors,
  catppuccinMacchiatoColors,
  catppuccinMochaColors,
  rosePineColors,
  rosePineMoonColors,
  rosePineDawnColors,
  draculaColors,
  nordColors,
  solarizedDarkColors,
  solarizedLightColors,
  gruvboxDarkColors,
  gruvboxLightColors,
} from './constants/colors';

export const themes: Theme[] = [
  {
    name: 'catppuccin-latte',
    displayName: 'Catppuccin Latte',
    type: 'light',
    colors: catppuccinLatteColors,
    accentColors: {
      rosewater: catppuccinLatteColors.rosewater,
      flamingo: catppuccinLatteColors.flamingo,
      pink: catppuccinLatteColors.pink,
      mauve: catppuccinLatteColors.mauve,
      red: catppuccinLatteColors.red,
      maroon: catppuccinLatteColors.maroon,
      peach: catppuccinLatteColors.peach,
      yellow: catppuccinLatteColors.yellow,
      green: catppuccinLatteColors.green,
      teal: catppuccinLatteColors.teal,
      sky: catppuccinLatteColors.sky,
      sapphire: catppuccinLatteColors.sapphire,
      blue: catppuccinLatteColors.blue,
      lavender: catppuccinLatteColors.lavender,
    },
  },
  {
    name: 'catppuccin-frappe',
    displayName: 'Catppuccin Frappé',
    type: 'dark',
    colors: catppuccinFrappeColors,
    accentColors: {
      rosewater: catppuccinFrappeColors.rosewater,
      flamingo: catppuccinFrappeColors.flamingo,
      pink: catppuccinFrappeColors.pink,
      mauve: catppuccinFrappeColors.mauve,
      red: catppuccinFrappeColors.red,
      maroon: catppuccinFrappeColors.maroon,
      peach: catppuccinFrappeColors.peach,
      yellow: catppuccinFrappeColors.yellow,
      green: catppuccinFrappeColors.green,
      teal: catppuccinFrappeColors.teal,
      sky: catppuccinFrappeColors.sky,
      sapphire: catppuccinFrappeColors.sapphire,
      blue: catppuccinFrappeColors.blue,
      lavender: catppuccinFrappeColors.lavender,
    },
  },
  {
    name: 'catppuccin-macchiato',
    displayName: 'Catppuccin Macchiato',
    type: 'dark',
    colors: catppuccinMacchiatoColors,
    accentColors: {
      rosewater: catppuccinMacchiatoColors.rosewater,
      flamingo: catppuccinMacchiatoColors.flamingo,
      pink: catppuccinMacchiatoColors.pink,
      mauve: catppuccinMacchiatoColors.mauve,
      red: catppuccinMacchiatoColors.red,
      maroon: catppuccinMacchiatoColors.maroon,
      peach: catppuccinMacchiatoColors.peach,
      yellow: catppuccinMacchiatoColors.yellow,
      green: catppuccinMacchiatoColors.green,
      teal: catppuccinMacchiatoColors.teal,
      sky: catppuccinMacchiatoColors.sky,
      sapphire: catppuccinMacchiatoColors.sapphire,
      blue: catppuccinMacchiatoColors.blue,
      lavender: catppuccinMacchiatoColors.lavender,
    },
  },
  {
    name: 'catppuccin-mocha',
    displayName: 'Catppuccin Mocha',
    type: 'dark',
    colors: catppuccinMochaColors,
    accentColors: {
      rosewater: catppuccinMochaColors.rosewater,
      flamingo: catppuccinMochaColors.flamingo,
      pink: catppuccinMochaColors.pink,
      mauve: catppuccinMochaColors.mauve,
      red: catppuccinMochaColors.red,
      maroon: catppuccinMochaColors.maroon,
      peach: catppuccinMochaColors.peach,
      yellow: catppuccinMochaColors.yellow,
      green: catppuccinMochaColors.green,
      teal: catppuccinMochaColors.teal,
      sky: catppuccinMochaColors.sky,
      sapphire: catppuccinMochaColors.sapphire,
      blue: catppuccinMochaColors.blue,
      lavender: catppuccinMochaColors.lavender,
    },
  },
  {
    name: 'rose-pine',
    displayName: 'Rosé Pine',
    type: 'dark',
    colors: rosePineColors,
    accentColors: {
      love: rosePineColors.love,
      gold: rosePineColors.gold,
      rose: rosePineColors.rose,
      pine: rosePineColors.pine,
      foam: rosePineColors.foam,
      iris: rosePineColors.iris,
    },
  },
  {
    name: 'rose-pine-moon',
    displayName: 'Rosé Pine Moon',
    type: 'dark',
    colors: rosePineMoonColors,
    accentColors: {
      love: rosePineMoonColors.love,
      gold: rosePineMoonColors.gold,
      rose: rosePineMoonColors.rose,
      pine: rosePineMoonColors.pine,
      foam: rosePineMoonColors.foam,
      iris: rosePineMoonColors.iris,
    },
  },
  {
    name: 'rose-pine-dawn',
    displayName: 'Rosé Pine Dawn',
    type: 'light',
    colors: rosePineDawnColors,
    accentColors: {
      love: rosePineDawnColors.love,
      gold: rosePineDawnColors.gold,
      rose: rosePineDawnColors.rose,
      pine: rosePineDawnColors.pine,
      foam: rosePineDawnColors.foam,
      iris: rosePineDawnColors.iris,
    },
  },
  {
    name: 'dracula',
    displayName: 'Dracula',
    type: 'dark',
    colors: draculaColors,
    accentColors: {
      cyan: draculaColors.cyan,
      green: draculaColors.green,
      orange: draculaColors.orange,
      pink: draculaColors.pink,
      purple: draculaColors.purple,
      red: draculaColors.red,
      yellow: draculaColors.yellow,
    },
  },
  {
    name: 'nord',
    displayName: 'Nord',
    type: 'dark',
    colors: {
      ...nordColors.polarNight,
      ...nordColors.snowStorm,
      ...nordColors.frost,
      ...nordColors.aurora,
    },
    accentColors: {
      ...nordColors.frost,
      ...nordColors.aurora,
    },
  },
  {
    name: 'solarized-dark',
    displayName: 'Solarized Dark',
    type: 'dark',
    colors: solarizedDarkColors,
    accentColors: {
      yellow: solarizedDarkColors.yellow,
      orange: solarizedDarkColors.orange,
      red: solarizedDarkColors.red,
      magenta: solarizedDarkColors.magenta,
      violet: solarizedDarkColors.violet,
      blue: solarizedDarkColors.blue,
      cyan: solarizedDarkColors.cyan,
      green: solarizedDarkColors.green,
    },
  },
  {
    name: 'solarized-light',
    displayName: 'Solarized Light',
    type: 'light',
    colors: solarizedLightColors,
    accentColors: {
      yellow: solarizedLightColors.yellow,
      orange: solarizedLightColors.orange,
      red: solarizedLightColors.red,
      magenta: solarizedLightColors.magenta,
      violet: solarizedLightColors.violet,
      blue: solarizedLightColors.blue,
      cyan: solarizedLightColors.cyan,
      green: solarizedLightColors.green,
    },
  },
  {
    name: 'gruvbox-dark',
    displayName: 'Gruvbox Dark',
    type: 'dark',
    colors: gruvboxDarkColors,
    accentColors: {
      red: gruvboxDarkColors.red,
      green: gruvboxDarkColors.green,
      yellow: gruvboxDarkColors.yellow,
      blue: gruvboxDarkColors.blue,
      purple: gruvboxDarkColors.purple,
      aqua: gruvboxDarkColors.aqua,
      orange: gruvboxDarkColors.orange,
    },
  },
  {
    name: 'gruvbox-light',
    displayName: 'Gruvbox Light',
    type: 'light',
    colors: gruvboxLightColors,
    accentColors: {
      red: gruvboxLightColors.red,
      green: gruvboxLightColors.green,
      yellow: gruvboxLightColors.yellow,
      blue: gruvboxLightColors.blue,
      purple: gruvboxLightColors.purple,
      aqua: gruvboxLightColors.aqua,
      orange: gruvboxLightColors.orange,
    },
  },
];
