import { Theme } from './shared/types/themes';
import { colorTokens } from './styles/theme/tokens';

export const themes: Theme[] = [
  {
    name: 'catppuccin-latte',
    displayName: 'Catppuccin Latte',
    type: 'light',
    colors: colorTokens.catppuccin.latte,
    accentColors: {
      rosewater: colorTokens.catppuccin.latte.rosewater,
      flamingo: colorTokens.catppuccin.latte.flamingo,
      pink: colorTokens.catppuccin.latte.pink,
      mauve: colorTokens.catppuccin.latte.mauve,
      red: colorTokens.catppuccin.latte.red,
      maroon: colorTokens.catppuccin.latte.maroon,
      peach: colorTokens.catppuccin.latte.peach,
      yellow: colorTokens.catppuccin.latte.yellow,
      green: colorTokens.catppuccin.latte.green,
      teal: colorTokens.catppuccin.latte.teal,
      sky: colorTokens.catppuccin.latte.sky,
      sapphire: colorTokens.catppuccin.latte.sapphire,
      blue: colorTokens.catppuccin.latte.blue,
      lavender: colorTokens.catppuccin.latte.lavender,
    },
  },
  {
    name: 'catppuccin-frappe',
    displayName: 'Catppuccin Frappé',
    type: 'dark',
    colors: colorTokens.catppuccin.frappe,
    accentColors: {
      rosewater: colorTokens.catppuccin.frappe.rosewater,
      flamingo: colorTokens.catppuccin.frappe.flamingo,
      pink: colorTokens.catppuccin.frappe.pink,
      mauve: colorTokens.catppuccin.frappe.mauve,
      red: colorTokens.catppuccin.frappe.red,
      maroon: colorTokens.catppuccin.frappe.maroon,
      peach: colorTokens.catppuccin.frappe.peach,
      yellow: colorTokens.catppuccin.frappe.yellow,
      green: colorTokens.catppuccin.frappe.green,
      teal: colorTokens.catppuccin.frappe.teal,
      sky: colorTokens.catppuccin.frappe.sky,
      sapphire: colorTokens.catppuccin.frappe.sapphire,
      blue: colorTokens.catppuccin.frappe.blue,
      lavender: colorTokens.catppuccin.frappe.lavender,
    },
  },
  {
    name: 'catppuccin-macchiato',
    displayName: 'Catppuccin Macchiato',
    type: 'dark',
    colors: colorTokens.catppuccin.macchiato,
    accentColors: {
      rosewater: colorTokens.catppuccin.macchiato.rosewater,
      flamingo: colorTokens.catppuccin.macchiato.flamingo,
      pink: colorTokens.catppuccin.macchiato.pink,
      mauve: colorTokens.catppuccin.macchiato.mauve,
      red: colorTokens.catppuccin.macchiato.red,
      maroon: colorTokens.catppuccin.macchiato.maroon,
      peach: colorTokens.catppuccin.macchiato.peach,
      yellow: colorTokens.catppuccin.macchiato.yellow,
      green: colorTokens.catppuccin.macchiato.green,
      teal: colorTokens.catppuccin.macchiato.teal,
      sky: colorTokens.catppuccin.macchiato.sky,
      sapphire: colorTokens.catppuccin.macchiato.sapphire,
      blue: colorTokens.catppuccin.macchiato.blue,
      lavender: colorTokens.catppuccin.macchiato.lavender,
    },
  },
  {
    name: 'catppuccin-mocha',
    displayName: 'Catppuccin Mocha',
    type: 'dark',
    colors: colorTokens.catppuccin.mocha,
    accentColors: {
      rosewater: colorTokens.catppuccin.mocha.rosewater,
      flamingo: colorTokens.catppuccin.mocha.flamingo,
      pink: colorTokens.catppuccin.mocha.pink,
      mauve: colorTokens.catppuccin.mocha.mauve,
      red: colorTokens.catppuccin.mocha.red,
      maroon: colorTokens.catppuccin.mocha.maroon,
      peach: colorTokens.catppuccin.mocha.peach,
      yellow: colorTokens.catppuccin.mocha.yellow,
      green: colorTokens.catppuccin.mocha.green,
      teal: colorTokens.catppuccin.mocha.teal,
      sky: colorTokens.catppuccin.mocha.sky,
      sapphire: colorTokens.catppuccin.mocha.sapphire,
      blue: colorTokens.catppuccin.mocha.blue,
      lavender: colorTokens.catppuccin.mocha.lavender,
    },
  },
  {
    name: 'rose-pine',
    displayName: 'Rosé Pine',
    type: 'dark',
    colors: colorTokens['rose-pine'],
    accentColors: {
      love: colorTokens['rose-pine'].love,
      gold: colorTokens['rose-pine'].gold,
      rose: colorTokens['rose-pine'].rose,
      pine: colorTokens['rose-pine'].pine,
      foam: colorTokens['rose-pine'].foam,
      iris: colorTokens['rose-pine'].iris,
    },
  },
  {
    name: 'rose-pine-moon',
    displayName: 'Rosé Pine Moon',
    type: 'dark',
    colors: colorTokens['rose-pine-moon'],
    accentColors: {
      love: colorTokens['rose-pine-moon'].love,
      gold: colorTokens['rose-pine-moon'].gold,
      rose: colorTokens['rose-pine-moon'].rose,
      pine: colorTokens['rose-pine-moon'].pine,
      foam: colorTokens['rose-pine-moon'].foam,
      iris: colorTokens['rose-pine-moon'].iris,
    },
  },
  {
    name: 'rose-pine-dawn',
    displayName: 'Rosé Pine Dawn',
    type: 'light',
    colors: colorTokens['rose-pine-dawn'],
    accentColors: {
      love: colorTokens['rose-pine-dawn'].love,
      gold: colorTokens['rose-pine-dawn'].gold,
      rose: colorTokens['rose-pine-dawn'].rose,
      pine: colorTokens['rose-pine-dawn'].pine,
      foam: colorTokens['rose-pine-dawn'].foam,
      iris: colorTokens['rose-pine-dawn'].iris,
    },
  },
  {
    name: 'dracula',
    displayName: 'Dracula',
    type: 'dark',
    colors: colorTokens.dracula,
    accentColors: {
      cyan: colorTokens.dracula.cyan,
      green: colorTokens.dracula.green,
      orange: colorTokens.dracula.orange,
      pink: colorTokens.dracula.pink,
      purple: colorTokens.dracula.purple,
      red: colorTokens.dracula.red,
      yellow: colorTokens.dracula.yellow,
    },
  },
  {
    name: 'nord',
    displayName: 'Nord',
    type: 'dark',
    colors: {
      ...colorTokens.nord['polar-night'],
      ...colorTokens.nord['snow-storm'],
      ...colorTokens.nord.frost,
      ...colorTokens.nord.aurora,
    },
    accentColors: {
      ...colorTokens.nord.frost,
      ...colorTokens.nord.aurora,
    },
  },
  {
    name: 'solarized-dark',
    displayName: 'Solarized Dark',
    type: 'dark',
    colors: colorTokens['solarized-dark'],
    accentColors: {
      yellow: colorTokens['solarized-dark'].yellow,
      orange: colorTokens['solarized-dark'].orange,
      red: colorTokens['solarized-dark'].red,
      magenta: colorTokens['solarized-dark'].magenta,
      violet: colorTokens['solarized-dark'].violet,
      blue: colorTokens['solarized-dark'].blue,
      cyan: colorTokens['solarized-dark'].cyan,
      green: colorTokens['solarized-dark'].green,
    },
  },
  {
    name: 'solarized-light',
    displayName: 'Solarized Light',
    type: 'light',
    colors: colorTokens['solarized-light'],
    accentColors: {
      yellow: colorTokens['solarized-light'].yellow,
      orange: colorTokens['solarized-light'].orange,
      red: colorTokens['solarized-light'].red,
      magenta: colorTokens['solarized-light'].magenta,
      violet: colorTokens['solarized-light'].violet,
      blue: colorTokens['solarized-light'].blue,
      cyan: colorTokens['solarized-light'].cyan,
      green: colorTokens['solarized-light'].green,
    },
  },
  {
    name: 'gruvbox-dark',
    displayName: 'Gruvbox Dark',
    type: 'dark',
    colors: colorTokens['gruvbox-dark'],
    accentColors: {
      red: colorTokens['gruvbox-dark'].red,
      green: colorTokens['gruvbox-dark'].green,
      yellow: colorTokens['gruvbox-dark'].yellow,
      blue: colorTokens['gruvbox-dark'].blue,
      purple: colorTokens['gruvbox-dark'].purple,
      aqua: colorTokens['gruvbox-dark'].aqua,
      orange: colorTokens['gruvbox-dark'].orange,
    },
  },
  {
    name: 'gruvbox-light',
    displayName: 'Gruvbox Light',
    type: 'light',
    colors: colorTokens['gruvbox-light'],
    accentColors: {
      red: colorTokens['gruvbox-light'].red,
      green: colorTokens['gruvbox-light'].green,
      yellow: colorTokens['gruvbox-light'].yellow,
      blue: colorTokens['gruvbox-light'].blue,
      purple: colorTokens['gruvbox-light'].purple,
      aqua: colorTokens['gruvbox-light'].aqua,
      orange: colorTokens['gruvbox-light'].orange,
    },
  },
];
