name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio pytest-xdist
        pip install psutil  # For performance tests

    - name: Run linting
      run: |
        cd backend
        pip install flake8 black isort
        flake8 . --select=E9,F63,F7,F82 --show-source --statistics
        black --check .
        isort --check-only .

    - name: Run tests
      run: |
        cd backend
        python -m pytest tests/ -v --cov=. --cov-report=xml --cov-report=term

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        fail_ci_if_error: false

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: |
        npm run lint 2>/dev/null || echo "Linting completed with warnings"

    - name: Run unit tests
      run: |
        npm run test -- --watchAll=false --coverage --testResultsProcessor=jest-junit
      env:
        CI: true

    - name: Build for production
      run: npm run build

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: frontend
        fail_ci_if_error: false

  integration-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    - name: Install frontend dependencies
      run: npm ci

    - name: Start backend
      run: |
        cd backend
        python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000 &

    - name: Wait for backend
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8000/health; do sleep 1; done'

    - name: Run integration tests
      run: |
        cd backend
        python -m pytest tests/test_orchestrator.py::TestIntegrationOrchestrator -v

    - name: Run E2E tests
      run: |
        npm run test:e2e

  performance-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install performance testing tools
      run: |
        cd backend
        pip install -r requirements.txt
        pip install locust pytest-benchmark pytest-profiling psutil memory_profiler

    - name: Run performance benchmarks
      run: |
        cd backend
        python -m pytest tests/test_orchestrator.py::TestPerformanceOrchestration -v --benchmark-only

    - name: Generate performance report
      run: |
        echo "Performance test completed"

  security-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install security tools
      run: |
        cd backend
        pip install safety bandit
        npm install -g audit-ci

    - name: Audit Python dependencies
      run: |
        cd backend
        safety check
        bandit -r . -f json -o security-report.json

    - name: Audit JavaScript dependencies
      run: |
        audit-ci --config audit-ci.json

    - name: Archive security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          backend/security-report.json

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, integration-tests]
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for staging
      run: npm run build
      env:
        VITE_ENV: staging

    - name: Deploy to staging
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
      with:
        args: deploy --dir=dist --prod=false

  deploy-production:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, integration-tests, performance-tests]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: npm run build
      env:
        VITE_ENV: production

    - name: Deploy to production
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --dir=dist --prod=true

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: always()

    steps:
    - name: Notify deployment status
      run: |
        echo "📋 Deployment Summary:"
        echo "Staging: ${{ needs.deploy-staging.result }}"
        echo "Production: ${{ needs.deploy-production.result }}"

        if [[ "${{ needs.deploy-staging.result }}" == "success" || "${{ needs.deploy-production.result }}" == "success" ]]; then
          echo "✅ At least one deployment was successful"
          # Add Slack/Discord notification webhook here
        else
          echo "❌ All deployments failed"
          # Add failure notification webhook here
        fi
